FROM runtime AS devel
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    moreutils \
    man-db \
    gcc-c++ \
    awk \
    sed \
    flex \
    bison \
    yacc \
    m4 \
    pandoc \
    cmake \
    meson \
    ninja-build \
    make \
    binutils \
    binutils-aarch64-linux-gnu \
    binutils-riscv64-linux-gnu \
    binutils-x86_64-linux-gnu \
    glibc-devel \
    clang \
    llvm \
    llvm-devel \
    clang-devel \
    rustup-init \
    nmap \
    docker-cli \
    docker-compose \
    docker-buildx \
    distribution-gpg-keys \
    podman \
    buildah \
    skopeo \
    crun \
    golang \
    apr-util-openssl \
    apr-util-lmdb \
    apr-util-sqlite \
    jre \
    ;
