FROM fedora AS base
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    dnf-plugins-core \
    coreutils \
    less \
    which \
    findutils \
    procps-ng \
    diffutils \
    patch \
    iputils \
    iproute \
    bash \
    acl \
    attr \
    util-linux \
    zstd \
    unzip \
    tar \
    bzip2 \
    xz \
    curl \
    wget \
    sqlite \
    openssl \
    nss \
    ca-certificates \
    git-core \
    libfido2 \
    libbpf \
    qrencode-libs \
    pciutils \
    usbutils \
    fuse3 \
    fuse-overlayfs \
    fuse3-libs \
    jq \
    yq \
    javapackages-filesystem \
    tzdata-java \
    lksctp-tools \
    xml-common \
    ;


FROM base AS shell-runtime
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    fish \
    git \
    vim \
    vim-default-editor \
    xxd \
    file \
    tree \
    qrencode \
    git-lfs \
    git-credential-oauth \
    git-credential-libsecret \
    openssh-clients \
    erofs-utils \
    squashfs-tools \
    squashfs-tools-ng \
    e2fsprogs \
    xfsprogs \
    perl \
    python3 \
    python3-setuptools \
    python3-pip \
    python3-pyyaml \
    yq \
    ripgrep \
    socat \
    nmap-ncat \
    nmap \
    docker-cli \
    docker-compose \
    docker-buildx \
    distribution-gpg-keys \
    podman \
    buildah \
    skopeo \
    crun \
    ;

FROM shell-runtime AS shell-devel
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    moreutils \
    gcc-c++ \
    meson \
    ninja-build \
    make \
    binutils \
    binutils-aarch64-linux-gnu \
    binutils-riscv64-linux-gnu \
    binutils-x86_64-linux-gnu \
    clang \
    llvm \
    llvm-devel \
    clang-devel \
    ;

FROM shell-runtime AS java-headless-runtime
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    jre-headless \
    ;

FROM base AS wayland-runtime
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  releasever=$(dnf --dump-variables | grep -e '^releasever =' | cut -d' ' -f 3-) && \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    dnf-plugins-core \
    "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${releasever}.noarch.rpm" \
    "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-${releasever}.noarch.rpm"
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    mesa-dri-drivers \
    mesa-vulkan-drivers-freeworld \
    mesa-va-drivers-freeworld \
    mesa-vdpau-drivers-freeworld \
    ttmkfdir \
    mkfontscale \
    libavcodec-freeworld \
    libdrm \
    libwayland-client \
    libwayland-server \
    libwayland-cursor \
    libwayland-egl \
    qt6-qtwayland \
    libinput \
    thunar \
    libglvnd \
    libarchive \
    libpng \
    ffmpeg \
    libva \
    libvdpau \
    default-fonts-core \
    jetbrains-mono-fonts-all \
    foot \
    kitty \
    wayland-utils \
    libva-utils \
    vulkan-tools \
    egl-utils \
    intel-media-driver \
    intel-mediasdk \
    gnome-themes-extra \
    adwaita-fonts-all \
    pipewire \
    pipewire-pulseaudio \
    pipewire-alsa \
    intel-vpl-gpu-rt \
    libheif-freeworld \
    wireplumber \
    vulkan-loader \
    pipewire-plugin-libcamera \
    pipewire-plugin-vulkan \
    pipewire-v4l2 \
    pipewire-utils \
    opus \
    libvorbis \
    flac-libs \
    vulkan-tools \
    egl-utils \
    drm_info \
    mpv \
    xcb-util \
    fuse3  \
    fuse-overlayfs \
    xorg-x11-server-Xwayland \
    xorg-x11-xauth \
    xorg-x11-xinit \
    dbus-x11 \
    setxkbmap \
    qt5-qtx11extras \
    ;

FROM wayland-runtime AS java-wayland-runtime
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    jre \
    ;

FROM scratch AS err-choose-a-target
RUN "ERROR: You need to choose a build target"
