FROM alpine AS tools
RUN apk add --no-cache gpg gpgv curl

FROM scratch AS keys
ADD --checksum=sha256:9ced1a0ce0216bbd16cb95847584892ddb3642718530407aeb5b6b0642d3d24a \
  https://repo.librewolf.net/pubkey.gpg /keys/librewolf.asc

FROM tools AS download
ARG TARGETOS
ARG TARGETARCH
COPY --from=keys /keys/ /keys/
RUN gpg --dearmor < /keys/librewolf.asc > /keys/librewolf.gpg
RUN set -eufx; \
  mkdir -p "/out/librewolf" "/out/bin" && \
  [ "${TARGETARCH}" == "amd64" ] && arch=x86_64 || arch="${TARGETARCH}"; \
  project_id=44042130 && \
  project_url="https://gitlab.com/api/v4/projects/${project_id}" && \
  release=$(curl -f -o /dev/null --write-out '%{redirect_url}' \
    "${project_url}/releases/permalink/latest" \
    | tr / '\n' | tail -n 1) && \
  release_url="${project_url}/packages/generic/librewolf/${release}" && \
  archive_file="librewolf-${release}-${TARGETOS}-${arch}-package.tar.xz" && \
  archive_url="${release_url}/${archive_file}" && \
  curl -Lf --parallel \
    -o "${archive_file}.sha256" "${archive_url}.sha256sum" \
    -o "${archive_file}.sig" "${archive_url}.sig" \
    -o "${archive_file}" "${archive_url}" \
    && \
  printf '*%s' "${archive_file}" | paste -d' ' "${archive_file}.sha256" - | sha256sum -c && \
  gpgv --verbose --keyring "/keys/librewolf.gpg" \
    "${archive_file}.sig" "${archive_file}" && \
  tar --strip-components=1 -xf "${archive_file}" -C "/out/librewolf" && \
  ln -sf "../librewolf/librewolf" "/out/bin/librewolf"

FROM scratch AS ext
COPY --from=download /out/ /
