FROM base AS runtime
RUN --mount=type=cache,id=dnf5-fedora,dst=/var/cache/libdnf5 \
  set -eufx; \
  dnf install -y --setopt=install_weak_deps=false \
    --setopt=keepcache=true \
    fish \
    git \
    vim \
    vim-default-editor \
    xxd \
    file \
    tree \
    qrencode \
    git-lfs \
    git-credential-oauth \
    git-credential-libsecret \
    openssh-clients \
    erofs-utils \
    squashfs-tools \
    squashfs-tools-ng \
    e2fsprogs \
    xfsprogs \
    perl \
    python3 \
    python3-setuptools \
    python3-pip \
    python3-pyyaml \
    yq \
    ripgrep \
    socat \
    nmap-ncat \
    ;

